#!/usr/bin/env bash
# A Bash script that displays the information about a school file in current directory

FILENAME="school"

if [ -e $FILENAME ]
then
	echo "school file exists"

	if [ -s $FILENAME ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f $FILENAME ]
	then
		echo "school file is a regular file"
	fi

else
	echo "school file does not exist"
fi
